function result = laplacian(J, Phi)
% Return the laplacian of Phi; [J, [J, Phi]]
result = commutator(J.x, commutator(J.x, Phi))...
    + commutator(J.y, commutator(J.y, Phi))...
    + commutator(J.z, commutator(J.z, Phi));
end